// Export the first array
export const categories = [
  { id: 1, name: "Home" },
  { id: 2, name: "Creditview" },
  {
    id: 3,
    name: "Sectors",
    subcategories: [
      {
        id: 301,
        name: "sectors",
        subchildcategories: [{ id: 302, name: "Corporates",  
           subminicategories:[{id: 303, name:"Aerospace/Defence" }],
           subminicategories:[{id: 304, name:"Agricultural/Products"}],
           subminicategories:[{id: 305, name:"Automotive"}],
           subminicategories:[{id: 306, name:"Chemicals"}],
           subminicategories:[{id: 307, name:"Construction & Homebuilding"}],
           subminicategories:[{id: 308, name:"Consumer Products"}],
           subminicategories:[{id: 309, name:"Finance Related"}],
           subminicategories:[{id: 310, name:"Healthcare"}],
           subminicategories:[{id: 311, name:"Leisure,Lodging & Entertainment"}],
           subminicategories:[{id: 312, name:"Leveraged Finance"}],
           subminicategories:[{id: 313, name:"Local Govvernment Financing Vegicles (LGFV)"}],
           subminicategories:[{id: 314, name:"Manufacturing"}],
           subminicategories:[{id: 315, name:"Media & Publishing"}],
           subminicategories:[{id: 316, name:"Metal & Mining"}],
           subminicategories:[{id: 317, name:"Oil & Gas"}],
           subminicategories:[{id: 318, name:"Paper, Packaging & Forest Products"}],
           subminicategories:[{id: 319, name:"Pharmaceuticals"}],
           subminicategories:[{id: 320, name:"Real Estate"}],
           subminicategories:[{id: 321, name:"Retail & Business Products"}],
           subminicategories:[{id: 322, name:"Services"}],
           subminicategories:[{id: 323, name:"Technology"}],
           subminicategories:[{id: 324, name:"Telecommunication"}],
           subminicategories:[{id: 325, name:"Trading Company"}],
           subminicategories:[{id: 326, name:"Transportation"}],
           subminicategories:[{id: 327, name:"Utilities"}],
           subminicategories:[{id: 328, name:"View Corporates"}],

        }],
      },

      { id: 401, name: "Financial Institutions",
        
       },
       { id: 402, name: "Funds & Asset Management" },
       { id: 403, name: "Infrastructure & Project Finance" },
       { id: 404, name: "Insurance" },
       { id: 405, name: "Sovereign & Supranational" },
       { id: 406, name: "Structured Finance" },
       { id: 407, name: "Sub-Sovereign" },
       { id: 408, name: "U.S. Public Finance" },
      

    ],
  },
  { id: 4, name: "Research & Reports" },
  { id: 5, name: "Topics" },
  { id: 6, name: "Insights & Events" },
  { id: 7, name: "Tools" },
  { id: 8, name: "Explore Moodys" },
  { id: 9, name: "Who we Serve" },
  { id: 10, name: "Solutions" },
  { id: 11, name: "Capabilities" },
  { id: 12, name: "About Us" },
  { id: 13, name: "Get In Touch" },
  { id: 14, name: "Support" },
  { id: 15, name: "Preferences" },
  { id: 16, name: "Language" },
];
